common/modules/nam/controllers/ComplainController.php
<?php

namespace common\modules\nam\controllers;

use Yii;
use common\modules\nam\controllers\LanguageController;
use common\modules\nam\models\content\Content;
use common\modules\nam\models\complain\Complain;
use common\modules\nam\models\event\Action;
use common\modules\nam\models\event\Event;
use common\modules\nam\models\complain\ComplainSearch;
use common\modules\nam\models\configuration\Configuration;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\modules\nam\controllers\EventController;

/**
 * ComplainController implements the CRUD actions for Complain model.
 */
class ComplainController extends LanguageController
{
	
	private $content;
	
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Complaint models.
     * @return mixed
     */
    public function actionIndex($id){
    	//Increment the complain values
    	$model = Content::findOne($id);
    	$model->num_of_complaints++;
    	$model->save();
    	
    	$user = \Yii::$app->user->identity->id;
    	$sql = 'select * from complaint where user = '.$user.' && content ='.$id;
    	$query = Complain::findBySql($sql);
    	
    	//You can make a complain
    	if(is_null($query)){
    		$searchModel = new ComplainSearch();
    		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    		
    		return $this->render('index', [
    				'searchModel' => $searchModel,
    				'dataProvider' => $dataProvider,
    		]);
    	//You already do the complain
    	}else{
    		return $this->render('norm/index');
    	}
    }

    /**
     * Displays a single Complaint model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Complaint model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Complaint model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Complaint model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Complaint the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Complain::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionNew($content_id, $section){
    	$model = Content::findOne($content_id);
    	
    	//Create and fill the fields of the new complaint
    	$complaint = new Complain();
    	$complaint->content = $content_id ; //Give the category form the content
    	$user = $this->getActualUser();
    	$complaint->user = $user;
    	$complaint->complain_category = $model->category;
    	
    	if(Configuration::UNIQUECOMPLAINTS){
    		$query = Complain::find()->where(['user' => $user, 'content' => $content_id])->one();
    		
    		if(is_null($query)){
    			$complaint->save();
    			//Increment the number of complaint of the content
    			$model->num_of_complaints++;
    			$model->save();
    			//Create the complaint event
    			EventController::createEvent($section,$user,$content_id,$action=ACTION::COMPLAIN); //Noupload action
    		}else{
    			Yii::$app->session->setFlash('error', Yii::t('message','You already complain this content!'));
    		}
    	}else{
    		$complaint->save();
    		//Increment the number of complaint of the content
    		$model->num_of_complaints++;
    		$model->save();
    		//Create the complaint event
    		EventController::createEvent($section,$user,$content_id,$action=ACTION::COMPLAIN); //Noupload action
    	}
    	
    	switch ($section){
    		case 1:
    			$sectionText = 'reporter';
    			break;
    		case 2:
    			$sectionText = 'forum';
    			break;
    		case 3:
    			$sectionText = 'imagevideo';
    			break;
    	}
    	
    	$this->redirect(["content/".$sectionText]);
    }
    
    private function getActualUser(){
    	return \Yii::$app->user->identity->id;
    }
}

common/modules/nam/controllers/NormController.php
<?php

namespace common\modules\nam\controllers;

use Yii;
use yii\helpers\Html;
use common\modules\nam\controllers\LanguageController;
use common\modules\nam\models\norm\Argument;
use common\modules\nam\models\norm\Norm;
use common\modules\nam\models\content\Content;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\modules\nam\models\norm\ArgumentRate;
use common\modules\nam\models\event\Action;

/**
 * NormController implements the CRUD actions for Norm model.
 */
class NormController extends LanguageController
{

	const NORM_ACTIVE = 2;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Norm models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Norm::find(),
        ]);
				foreach($dataProvider->getModels() as $model){
					$this->shouldCloseNorm($model);
				}
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($content)
    {
        return $this->render('view', ['model' => $this->findModel($content->getNorm())]);
    }


    /**
     * Displays a single Argument model.
     * @param integer $id
     * @return mixed
     */
    public function actionViewargument($id)
    {
    	$model = Argument::findOne($id);
    	return $this->render('../argument/view', ['model' => $model]);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionDetail($category,$section){
     	$model = Norm::find()->where(['complain_category' => $category, 'section' => [$section,4]])->orderBy('id')->one();
    	return $this->showNorm($model,$section);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionDetailargument($norm, $category,$section){
    	$model = Norm::find()->where(['id' => $norm])->orderBy('id')->one();
    	return $this->showNorm($model,$section);

    	}

    private function showNorm($model,$section){
    	$user = \Yii::$app->user->identity->id;
    	if(!is_null($model)){

	    	$users = Argument::find()->select(['user'],'distinct')->where(['norm' => $model->id])->all();
	    	$num_users = sizeof($users);
	    	//      	var_dump($num_users);
	    	//      	$arguments = Argument::find()->select(['id'])->where(['norm' => $model->id])->all();

	    	//      	$array = array();
	    	//     	foreach($arguments as $a){
	    	//      		$userArgument = ArgumentRate::find()->select(['id_user'],'distinct')->where(['id_argument' => $a['id']])->one();
	    		//      		array_push($array, $userArgument['id_user']);
	    		//      	}
	    		//      	echo sizeof($array);
	    		//      	$uniques = array_unique($array);
	    		//      	$usersRate = sizeof($uniques);
	    		//      	echo $usersRate;
    	}

    		return $this->render('detail', ['model' => $model]);
    }

		public static function shouldCloseNorm($model){
			Yii::error($model->closing);
			if($model->active==0 && $model->closing <= time()){
				Yii::error($model->closing);
				if($model->rating>2){
					$model->active = 1;
					EventController::createEvent($model->section,$model->user,null,$action=ACTION::ACTIVENORM,null,null,$model->id);
					//Yii::$app->session->setFlash('success', 'The norm was activated!');
				}else{
					$model->active = 2;
				}
				$model->save();
			}
		}
    public function actionAddargument($norm, $positive, $category, $section){
    	$model = new Argument();
    	$model->norm = $norm;
    	$user = \Yii::$app->user->identity->id;
    	$model->user = $user;
    	$model->type = $positive;
			$model->rate = 0;
			$model->numrate = 0;
			$model->weight = 0;

    	if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	EventController::createEvent($section,$user,null,$action=ACTION::ADDARGUMENT,$model->id,null,$norm); //add argument action

    		Yii::$app->session->setFlash('success', 'Your argument was added!');
    		$model = $this->findModel($norm);
    		return $this->redirect(['detailargument', 'norm'=>$norm, 'category' => $category, 'section' => $section]);
    	} else {
    		return $this->render('/argument/create', ['model' => $model]);
    	}
    }

    public function actionRate($rating,$id_argument, $norm, $section, $category){
    	$model = new ArgumentRate();
    	$user = \Yii::$app->user->identity->id;
    	$model->id_user = $user;
    	$model->id_argument = $id_argument;
    	$model->rate = $rating;

    	if($model->save()){
    		EventController::createEvent($section,$user,null,$action=ACTION::RATEARGUMENT,$id_argument,$rating); //Noupload action
				OWAController::updateRatingArgument($id_argument);
    		Yii::$app->session->setFlash('success', 'Your rate was added!');
    	}else{
    		Yii::$app->session->setFlash('danger', 'Your rate was not added!');
    	}
    	$model = $this->findModel($norm);

    	return $this->redirect(['detail', 'category' => $category, 'section' => $section]);
    }

    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id, $category, $section)
    {
        $norm = new Norm();
        $norm->name = "Forbidden to upload";
        $norm->modality = 1;
        $norm->action = 1;
        $norm->complain_category = $category;
        $norm->section = $section;
        $norm->section = $section;
        $norm->rating = 0;
        $norm->ratingpos = 0;
        $norm->ratingneg = 0;
        $user = \Yii::$app->user->identity->id;

        if ($norm->load(Yii::$app->request->post()) && $norm->save()) {
        	EventController::createEvent($section,$user,null,$action=ACTION::CREATENORM,null,null,$norm->id); //Noupload action

        	//Add the first positive argument
        	$modelArgument = new Argument();
        	$modelArgument->norm = $norm->id;
        	$modelArgument->user = \Yii::$app->user->identity->id;
        	$modelArgument->type = 1;
					$modelArgument->rate = 0;
					$modelArgument->numrate = 0;
					$modelArgument->weight = 0;

        	//$content = Content::findOne($id); //Find the model
        	$modelArgument->description = $id;
        	//$modelArgument->description = "Forbidden to upload this content ".$id;
        	if($modelArgument->save()){
        		EventController::createEvent($norm->section,$user,null,$action=ACTION::ADDARGUMENT,$modelArgument->id,null,$norm->id); //add argument action
        		Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
        	}else{
        		Yii::$app->session->setFlash('danger', Yii::t('message','Your norm was not added!'));
        	}

    		return $this->redirect(['detail', 'category' => $category, 'section' => $norm->section]);
       	} else {
            return $this->render('create', ['model' => $norm]);
        }
    }


    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreatenorm()
    {
    	$norm = new Norm();
    	$norm->name = "Forbidden to upload";
    	$norm->modality = 1;
    	$norm->action = 1;
    	$norm->rating = 0;
    	$norm->ratingpos = 0;
    	$norm->ratingneg = 0;

    	$user = \Yii::$app->user->identity->id;

    	if ($norm->load(Yii::$app->request->post()) && $norm->save()) {
    		EventController::createEvent($norm->section,$user,null,$action=ACTION::CREATENORM,null,null,$norm->id); //Noupload action
    		Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
    		return $this->redirect(['index']);
    	} else {
    		return $this->render('create', ['model' => $norm]);
    	}
    }

    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate2()
    {
    	$model = new Norm();
    	$model->modality = 1;
    	$model->action = 1;
    	$model->active = 0;

    	$user = \Yii::$app->user->identity->id;

    	if ($model->load(Yii::$app->request->post()) && $model->save()) {
    		EventController::createEvent($section,$user,null,$action=ACTION::CREATENORM,null,null,$model->id); //Noupload action

			//Add the first positive argument
        	$modelArgument = new Argument();
        	$modelArgument->norm = $model->id;
        	$modelArgument->user = \Yii::$app->user->identity->id;
        	$modelArgument->type = 1;
        	$modelArgument->description = "This is automatic argument";
        	$modelArgument->save();;
	    	Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
    		return $this->render('detail', ['model' => $model]);
    	} else {
    		return $this->render('create', ['model' => $model]);
    	}
    }

    /**
     * Updates an existing Norm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', ['model' => $model]);
        }
    }

    /**
     * Deletes an existing Norm model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */

common/modules/nam/views/content/_footer_menu.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Content */
/* @var $form yii\widgets\ActiveForm */
?>
<?php 
if($model->alertView()){
?>
<span class="label label-default"><?=Yii::t('button', 'Views')?> <?= Html::encode($model['num_of_views']);?></span>  
<?php 
}else{
?>
<span class="label label-success"><?=Yii::t('button', 'Views')?> <?= Html::encode($model['num_of_views']);?></span>  

<?php
}
if($model->alertComplain()){ 
?>
	<span class="label label-default"><?=Yii::t('button', 'Complaints')?> <?= Html::encode($model['num_of_complaints']);?></span>
	<span class="label label-danger"> <?= "Conflict detected!" ?></span>
<?php 
}else{ ?>
	<span class="label label-default"><?=Yii::t('button', 'Complaints')?> <?= Html::encode($model['num_of_complaints']);?></span>
<?php } ?>


<?php 
if(!$model->isNorm($model['owner'])){ 
?>
	<span class="label label-danger"><?= "Forbidden by norm" ?></span>
<?php 
}
?>

common/modules/nam/views/content/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Content */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="content-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'category', 'category');?>

    <?= $form->field($model, 'section')->textInput() ?>

    <?= $form->field($model, 'owner')->textInput() ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'type')->textInput(['maxlength' => 20]) ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'message')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'num_of_views')->textInput() ?>

    <?= $form->field($model, 'num_of_complaints')->textInput() ?>

    <?= $form->field($model, 'violated_norm')->textInput() ?>
$form->textField($model->author,'username');
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/nam/views/content/_forum_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\modules\nam\models\content\Content;
use common\models\User;



/* @var $this yii\web\View */
/* @var $model frontend\models\Content */

// $this->title = $model['title'];
// $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Contents'), 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
  <ul class="media-list forum">
    <!-- Forum Post -->
    <li class="media well">
      <div class="pull-left user-info">
        <img class="avatar img-circle img-thumbnail" src="images/guest.png" width="64" alt='User'>
          <?= Html::a(Yii::t('app', $model->users['username']), ['/nam/user/view']);?>        
      </div>
      <div class="media-body">
        <!-- Post Info Buttons -->
         <?= Html::a(Html::encode($model['title']), ['view', 'id' => $model['id']], ['class' => '']) ?>
        <div class="pull-right">
               <?= Html::encode($model['actualdate']) ?>
        </div>
        <br>
        <p><?= Html::encode($model['message']);?></p>
		<?php 
        	$x = $model->getState();
        	switch($x){
        		case Content::STATE_NORMAL:
        			?><div class="pull-right">
        			<?php 
        			if(!$model->isNorm()){
        				echo Html::a(Yii::t('button', 'Discuss norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);
        			}else{
        			   echo Html::a(Yii::t('button', 'Create norm'), ['norm/create', 'id' => $model['id'], 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);
        			}?>
        			</div>
        			<?php 
        			break;
        		case Content::STATE_COMPLAIN:
        			?>
        			<?= $this->render('_footer_menu', ['model' => $model]);?>
        			
        			<div class="pull-right">
        			<?php echo Html::a(Yii::t('button', 'Complain'), ['complain/new', 'content_id' => $model['id'], 'section' => $section], ['class' => 'btn btn-danger']);?>
        			</div>
        			<?php break;
        		case Content::STATE_NORM:
        			echo $this->render('_footer_menu', ['model' => $model]);
        			        			
        			?><div class="pull-right">
        			<?php echo Html::a(Yii::t('button', 'View norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);?>
        			</div>
        			<?php 
        			break;
				case Content::STATE_NORMAL_CONTENT :
        			break;
        	}
        ?>
      </div>
    </li>
  </ul>

common/modules/nam/views/content/_imagevideo_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\modules\nam\models\content\Content;

/* @var $this yii\web\View */
/* @var $model frontend\models\Content */

// $this->title = $model['title'];
// $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Contents'), 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>


<ul class="list-unstyled video-list-thumbs">
	<li class="col-lg-3 col-sm-5 col-xs-4">		
		<h2><?= Html::a(Html::encode($model['title']), ['view', 'id' => $model['id']]) ?></h2>
		    <?php 
		    if($model['type']=='Video'){
		    	?>
		    	<img src=<?= Html::encode($model['url'])?> alt="" class="img-responsive" height="260px" />
		    	<span class="glyphicon glyphicon-play-circle"></span>
		    	<span class="duration"><?= Html::encode($model['message'])?></span>
		    <?php }else{ ?>
		    	<img src=<?= Html::encode($model['url'])?> alt=<?= Html::encode($model['message'])?> class="img-responsive" height="260px" />
		    <?php };?>
			<?php
        	$x = $model->getState();
        	switch($x){
        		case Content::STATE_NORMAL: 
        			if(!$model->isNorm()){
        				echo Html::a(Yii::t('button', 'Discuss norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'label label-primary']);
        			}else{
        				echo Html::a(Yii::t('button', 'Create norm'), ['norm/create', 'id' => $model['id'], 'category' => $model['category'], 'section' => $model['section']], ['class' => 'label label-primary']);
        			}
        			break;
        		case Content::STATE_COMPLAIN:
        			 echo $this->render('_footer_menu', ['model' => $model]);
        			 echo Html::a(Yii::t('button', 'Complain'), ['complain/new', 'content_id' => $model['id'], 'section' => $model['section']], ['class' => 'label label-danger']);
        			 break;
        		case Content::STATE_NORM:
        			echo $this->render('_footer_menu', ['model' => $model]);
					echo Html::a(Yii::t('button', 'View norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'label label-primary']);
        			break;
        		case Content::STATE_NORMAL_CONTENT:
        				break;
        	}
        	?>
	</li>
</ul>
   
    

common/modules/nam/views/content/_menu.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\modules\nam\models\content\Content;

/* @var $this yii\web\View */
/* @var $model frontend\models\Content */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="menu_content">
    <p>    
    	<?= Html::a(Yii::t('button', 'Post spam content', ['modelClass' => 'Content',]), ['upload', 'type' => Content::CONTENT_SPAM, 'section'=>$section], ['class' => 'btn btn-primary']) ?>
    	<?php //echo Html::a(Yii::t('button', 'Post erotic/pornographic content', ['modelClass' => 'Content',]), ['upload', 'type' => 2, 'section'=>$section], ['class' => 'btn btn-primary']) ?>
    	<?php //echo Html::a(Yii::t('button', 'Post violent content', ['modelClass' => 'Content',]), ['upload', 'type' => 3, 'section'=>$section], ['class' => 'btn btn-primary']) ?>
    	<?php //echo Html::a(Yii::t('button', 'I\'m angry, I want to insult', ['modelClass' => 'Content',]), ['upload', 'type' => 4, 'section'=>$section], ['class' => 'btn btn-primary']) ?>
    	<?= Html::a(Yii::t('button', 'Post normal content', ['modelClass' => 'Content',]), ['upload', 'type' => Content::CONTENT_NORMAL, 'section'=>$section], ['class' => 'btn btn-primary']) ?>
    </p>
</div>
<br>

common/modules/nam/views/content/_reporter_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\modules\nam\models\content\Content;
use common\models\User;



/* @var $this yii\web\View */
/* @var $model frontend\models\Content */

// $this->title = $model['title'];
// $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Contents'), 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="row reporter-row">
	<div class="col-xs-8 col-xs-offset-2 slide-row">
		<div class="slide-content">	
			
				<h4><?= Html::a(Html::encode($model['title']), ['view', 'id' => $model['id']], ['class' => '']) ?></h4>
                <p>                
                	<?=Yii::t('other', 'Posted by')?>   <?= Html::a(Html::encode($model->users['username']), ['/nam/user/view']) ?> <?=Yii::t('other', 'on')?>  <?= Html::encode($model['actualdate']) ?>
                </p>
                <hr>
                <p>
                	<?= Html::encode($model['message']);?>
               		<!-- Message content -->
                </p> 
        </div>
			<?php 
        	$x = $model->getState();
        	switch($x){
        		case Content::STATE_NORMAL:
        			?><div class="slide-footer">
        			<?php 
        			if(!$model->isNorm()){
        				echo Html::a(Yii::t('button', 'Discuss norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);
        			}else{
        			   echo Html::a(Yii::t('button', 'Create norm'), ['norm/create', 'id' => $model['id'], 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);
        			}?>
        			</div>
        			<?php 
        			break;
        		case Content::STATE_COMPLAIN:
        			?>
        			<div class="slide-rating">
        			<?= $this->render('_footer_menu', ['model' => $model]);?>
        			</div>
        			<div class="slide-footer">
        			<?php echo Html::a(Yii::t('button', 'Complain'), ['complain/new', 'content_id' => $model['id'], 'section' => $section], ['class' => 'btn btn-danger']);?>
        			</div>
        			<?php break;
        		case Content::STATE_NORM:
        			?><div class="slide-rating">
        			<?php echo $this->render('_footer_menu', ['model' => $model]);?>
        			</div>        			
        			<div class="slide-footer">
        			<?php echo Html::a(Yii::t('button', 'View norm'), ['norm/detail', 'category' => $model['category'], 'section' => $model['section']], ['class' => 'btn btn-primary']);?>
        			</div>
        			<?php 
        			break;
        		case Content::STATE_NORMAL_CONTENT :
        			break;
        	}
        ?>
 	</div>
</div>	

common/modules/nam/views/content/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Content */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Content',
]);
// $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Contents'), 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="content-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/nam/views/content/forum.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

// $this->title = Yii::t('app', 'Contents');
// $this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <!-- Show the action menu that the user can do-->
     <?= $this->render('_menu', ['model' => $dataProvider, 'section'=>2]) ?>
</div>


<div class="container">
  <h1 class="page-header"><?=Yii::t('title', 'General topic')?></h1>
		<ul class="media-list forum">
			    <?= ListView::widget([
			        'dataProvider' => $dataProvider,
			        'itemOptions' => ['class' => 'item'],
			        'itemView' => function ($model, $key, $index, $widget) {
			        	return $this->render('_forum_view',['model' => $model, 'section' => 2]);
			        },
			        'emptyText' => '',
					'layout' => '{items}{pager}'])
			     ?>
		</ul>
	<h1 class="page-header"><?=Yii::t('title', 'Others topics')?></h1>
</div>