common/modules/nam/controllers/NormController.php
<?php

namespace common\modules\nam\controllers;

use Yii;
use yii\helpers\Html;
use common\modules\nam\controllers\LanguageController;
use common\modules\nam\models\norm\Argument;
use common\modules\nam\models\norm\Norm;
use common\modules\nam\models\content\Content;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\modules\nam\models\norm\ArgumentRate;
use common\modules\nam\models\event\Action;

/**
 * NormController implements the CRUD actions for Norm model.
 */
class NormController extends LanguageController
{

	const NORM_ACTIVE = 2;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Norm models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Norm::find(),
        ]);
				foreach($dataProvider->getModels() as $model){
					$this->shouldCloseNorm($model);
				}
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($content)
    {
        return $this->render('view', ['model' => $this->findModel($content->getNorm())]);
    }


    /**
     * Displays a single Argument model.
     * @param integer $id
     * @return mixed
     */
    public function actionViewargument($id)
    {
    	$model = Argument::findOne($id);
    	return $this->render('../argument/view', ['model' => $model]);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionDetail($category,$section){
     	$model = Norm::find()->where(['complain_category' => $category, 'section' => [$section,4]])->orderBy('id')->one();
    	return $this->showNorm($model,$section);
    }

    /**
     * Displays a single Norm model.
     * @param integer $id
     * @return mixed
     */
    public function actionDetailargument($norm, $category,$section){
    	$model = Norm::find()->where(['id' => $norm])->orderBy('id')->one();
    	return $this->showNorm($model,$section);

    	}

    private function showNorm($model,$section){
    	$user = \Yii::$app->user->identity->id;
    	if(!is_null($model)){

	    	$users = Argument::find()->select(['user'],'distinct')->where(['norm' => $model->id])->all();
	    	$num_users = sizeof($users);
	    	//      	var_dump($num_users);
	    	//      	$arguments = Argument::find()->select(['id'])->where(['norm' => $model->id])->all();

	    	//      	$array = array();
	    	//     	foreach($arguments as $a){
	    	//      		$userArgument = ArgumentRate::find()->select(['id_user'],'distinct')->where(['id_argument' => $a['id']])->one();
	    		//      		array_push($array, $userArgument['id_user']);
	    		//      	}
	    		//      	echo sizeof($array);
	    		//      	$uniques = array_unique($array);
	    		//      	$usersRate = sizeof($uniques);
	    		//      	echo $usersRate;
    	}

    		return $this->render('detail', ['model' => $model]);
    }

		public static function shouldCloseNorm($model){
			Yii::error($model->closing);
			if($model->active==0 && $model->closing <= time()){
				Yii::error($model->closing);
				if($model->rating>2){
					$model->active = 1;
					EventController::createEvent($model->section,$model->user,null,$action=ACTION::ACTIVENORM,null,null,$model->id);
					//Yii::$app->session->setFlash('success', 'The norm was activated!');
				}else{
					$model->active = 2;
				}
				$model->save();
			}
		}
    public function actionAddargument($norm, $positive, $category, $section){
    	$model = new Argument();
    	$model->norm = $norm;
    	$user = \Yii::$app->user->identity->id;
    	$model->user = $user;
    	$model->type = $positive;
			$model->rate = 0;
			$model->numrate = 0;
			$model->weight = 0;

    	if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	EventController::createEvent($section,$user,null,$action=ACTION::ADDARGUMENT,$model->id,null,$norm); //add argument action

    		Yii::$app->session->setFlash('success', 'Your argument was added!');
    		$model = $this->findModel($norm);
    		return $this->redirect(['detailargument', 'norm'=>$norm, 'category' => $category, 'section' => $section]);
    	} else {
    		return $this->render('/argument/create', ['model' => $model]);
    	}
    }

    public function actionRate($rating,$id_argument, $norm, $section, $category){
    	$model = new ArgumentRate();
    	$user = \Yii::$app->user->identity->id;
    	$model->id_user = $user;
    	$model->id_argument = $id_argument;
    	$model->rate = $rating;

    	if($model->save()){
    		EventController::createEvent($section,$user,null,$action=ACTION::RATEARGUMENT,$id_argument,$rating); //Noupload action
				OWAController::updateRatingArgument($id_argument);
    		Yii::$app->session->setFlash('success', 'Your rate was added!');
    	}else{
    		Yii::$app->session->setFlash('danger', 'Your rate was not added!');
    	}
    	$model = $this->findModel($norm);

    	return $this->redirect(['detail', 'category' => $category, 'section' => $section]);
    }

    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id, $category, $section)
    {
        $norm = new Norm();
        $norm->name = "Forbidden to upload";
        $norm->modality = 1;
        $norm->action = 1;
        $norm->complain_category = $category;
        $norm->section = $section;
        $norm->section = $section;
        $norm->rating = 0;
        $norm->ratingpos = 0;
        $norm->ratingneg = 0;
        $user = \Yii::$app->user->identity->id;

        if ($norm->load(Yii::$app->request->post()) && $norm->save()) {
        	EventController::createEvent($section,$user,null,$action=ACTION::CREATENORM,null,null,$norm->id); //Noupload action

        	//Add the first positive argument
        	$modelArgument = new Argument();
        	$modelArgument->norm = $norm->id;
        	$modelArgument->user = \Yii::$app->user->identity->id;
        	$modelArgument->type = 1;
					$modelArgument->rate = 0;
					$modelArgument->numrate = 0;
					$modelArgument->weight = 0;

        	//$content = Content::findOne($id); //Find the model
        	$modelArgument->description = $id;
        	//$modelArgument->description = "Forbidden to upload this content ".$id;
        	if($modelArgument->save()){
        		EventController::createEvent($norm->section,$user,null,$action=ACTION::ADDARGUMENT,$modelArgument->id,null,$norm->id); //add argument action
        		Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
        	}else{
        		Yii::$app->session->setFlash('danger', Yii::t('message','Your norm was not added!'));
        	}

    		return $this->redirect(['detail', 'category' => $category, 'section' => $norm->section]);
       	} else {
            return $this->render('create', ['model' => $norm]);
        }
    }


    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreatenorm()
    {
    	$norm = new Norm();
    	$norm->name = "Forbidden to upload";
    	$norm->modality = 1;
    	$norm->action = 1;
    	$norm->rating = 0;
    	$norm->ratingpos = 0;
    	$norm->ratingneg = 0;

    	$user = \Yii::$app->user->identity->id;

    	if ($norm->load(Yii::$app->request->post()) && $norm->save()) {
    		EventController::createEvent($norm->section,$user,null,$action=ACTION::CREATENORM,null,null,$norm->id); //Noupload action
    		Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
    		return $this->redirect(['index']);
    	} else {
    		return $this->render('create', ['model' => $norm]);
    	}
    }

    /**
     * Creates a new Norm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate2()
    {
    	$model = new Norm();
    	$model->modality = 1;
    	$model->action = 1;
    	$model->active = 0;

    	$user = \Yii::$app->user->identity->id;

    	if ($model->load(Yii::$app->request->post()) && $model->save()) {
    		EventController::createEvent($section,$user,null,$action=ACTION::CREATENORM,null,null,$model->id); //Noupload action

			//Add the first positive argument
        	$modelArgument = new Argument();
        	$modelArgument->norm = $model->id;
        	$modelArgument->user = \Yii::$app->user->identity->id;
        	$modelArgument->type = 1;
        	$modelArgument->description = "This is automatic argument";
        	$modelArgument->save();;
	    	Yii::$app->session->setFlash('success', Yii::t('message','Your norm was added!'));
    		return $this->render('detail', ['model' => $model]);
    	} else {
    		return $this->render('create', ['model' => $model]);
    	}
    }

    /**
     * Updates an existing Norm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', ['model' => $model]);
        }
    }

    /**
     * Deletes an existing Norm model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */

common/modules/nam/views/norm/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\modules\nam\models\complain\ComplainCategory;
use common\modules\nam\models\content\Section;
use common\modules\nam\models\event\Action;
use common\modules\nam\models\norm\Modality;
use yii\helpers\ArrayHelper;
use kartik\time\TimePicker;

/* @var $this yii\web\View */
/* @var $model frontend\models\Norm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="norm-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'complain_category')->textInput()->dropDownList(ArrayHelper::map(ComplainCategory::find()->all(),"id","description"))->label("Forbidden to upload content") ?>

    <?= $form->field($model, 'section')->textInput()->dropDownList(ArrayHelper::map(Section::find()->all(),"id","description"))->label("to section:") ?>

    <?= $form->field($model, 'closing')->widget(TimePicker::classname(),[
    'pluginOptions' => [
        'defaultTime' => '00:15',
        'showMeridian' => false
    ]
])->label("Time until this norm is closed:") ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('button', 'Create') : Yii::t('button', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/nam/views/norm/detail.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\modules\nam\models\norm\Argument;
use common\modules\nam\models\content\Content;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;
use kartik\popover\PopoverX;
use common\modules\nam\models\norm\ArgumentRate;
use kartik\rating\StarRating;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>



<br><br>
<h3><?php echo "Norm     ";
if($model->active==0){?>
	<span class="label label-default"><?= "Under discussion" ?></span>
<?php
		echo '<small>Time Remaining:'.gmdate('H:i',$model->closing-time()).'</small>';
}else if($model->active==2){?>
	<span class="label label-danger"><?= "Closed" ?></span>
	<?php
}else{?>
	<span class="label label-success"><?= "Active" ?></span>
<?php
}?>
</h3>
<div class="tree">
    <ul>
		<span><?=Yii::t('norm','Proposed Norm:')?></span>
		<li>
			<span><i class="glyphicon glyphicon-list"></i>
			<?=Yii::t('norm',$model['name']);?>
			<span title="Category" class="label label-danger"><?= Html::encode($model->complainCategory['description']);?></span>
			<?=Yii::t('norm','at');?>
			<span title="Section" class="label label-default"><?= Html::encode($model->section0['description']);?></span>
			<?=Yii::t('norm','section');?>
			</span>
			<?php generateStarIcons($model['rating']);?>

			<br></br>
			<!--<ul>-->
			<ul>
				<span id="arguments">
                <!--<li>-->
                	<span class="label label-success"><i class="icon-minus-sign"></i><?=Yii::t('norm','Arguments in favour')?></span> <?php generateStarIcons($model['ratingpos']);?>  <?php if(!$model->active) echo Html::a(Yii::t('button', 'Add'), ['norm/addargument', 'norm' => $model['id'], 'positive' => 1, 'category' => $model->complain_category, 'section' => $model->section], ['class' => 'label label-primary']);?>
                    <ul>
                    	<?php
                    	showArguments(1, $model);
                  		?>
                    </ul>
                <!--</li>-->
				</span>
				<span id="arguments">
                <!--<li>-->
                	<span class="label label-danger"><i class="icon-minus-sign"></i><?=Yii::t('norm','Arguments against')?></span> <?php generateStarIcons($model['ratingneg']);?>  <?php if(!$model->active) echo Html::a(Yii::t('button', 'Add'), ['norm/addargument', 'norm' => $model['id'], 'positive' => 2, 'category' => $model->complain_category, 'section' => $model->section], ['class' => 'label label-primary']);?>
                    <ul>
						<?php
                    	showArguments(2, $model);
                  		?>
                    </ul>
                <!--</li>-->
				</span>
			</ul>
            <!--</ul>-->
		</li>
	</ul>
</div>

<?php
/**
 * Function to show the arguments of the norm
 * @param unknown $type Type of the argument
 * @param unknown $model Norm model
 */
function showArguments($type, $model){
	$sql = 'select * from argument where type = '.$type.' && norm = '.$model['id'];
	$query = Argument::findBySql($sql);
	$dataProvider = new ActiveDataProvider(['query' => $query]);
	$models = $dataProvider->models;
	$rate = 0;
	foreach($models as $modelArgument){
		?><li>
			<?php
			$description = $modelArgument['description'];
			if(is_numeric($description)){
				$content = Content::findOne($description);
				echo 'Content such as '.Html::a(Html::encode($content['title']), ['/nam/content/view', 'id' => $modelArgument['description']], ['class' => '']) .' should not be published to upload this content ';
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }else{
				echo Html::encode($description)." ";
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }
			?>
	       <?php $content = '<form name="form" action="" method="get"> <input class="rating" data-max="5" data-min="1" id="input" type="number"/> </form>' ;?>
           <?php
	           if(ArgumentRate::isRated($modelArgument['id']) && (!$model->active)){
	           ?>	<span>Rate argument:<?php
	           	echo Html::a(Yii::t('button', '1'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>1, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '2'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>2, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '3'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>3, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '4'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>4, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '5'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>5, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	?></span>
	           	<?php
	           }
	           ?>
	   	</li>
<?php }
}



function generateStarIcons($number){
	//Full star
	$num = floor($number);
	$rest = $number-$num;
	echo '<i title="'.round($number,2).'">';
	for($i=0; $i<$num; $i++){
		echo '<i class="fa fa-star yellow"></i>';
	}

	//Half star
	if($rest >= 0.5){
		echo '<i class="fa fa-star-half-empty yellow"></i>';
		$i++;
	}

	//Empty star
	for($j=$i; $j<5; $j++){
		echo '<i class="fa fa-star-o yellow"></i>';
	}
	echo '</i>';
}
?>

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

common/modules/nam/views/norm/detailnoeditable.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\modules\nam\models\norm\Argument;
use common\modules\nam\models\content\Content;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;
use kartik\popover\PopoverX;
use common\modules\nam\models\norm\ArgumentRate;
use kartik\rating\StarRating;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>



<br><br>
<div class="tree">
    <ul>
		<li>
			<span><i class="glyphicon glyphicon-list"></i>
			<?=Yii::t('norm',$model['name']);?>
			<span title="Category" class="label label-danger"><?= Html::encode($model->categories['description']);?></span>
			<?=Yii::t('norm','at');?>
			<span title="Section" class="label label-default"><?= Html::encode($model->sections['description']);?></span>
			<?=Yii::t('norm','section');?>
			</span>
			<?php generateStarIcons($model['id']);?>
			<ul>
                <li>
                	<span class="label label-success"><i class="icon-minus-sign"></i><?=Yii::t('norm','Positive arguments')?></span> <?php generateStarIcons($model['ratingpos']);?>  <?= Html::a(Yii::t('button', 'Add'), ['norm/addargument', 'norm' => $model['id'], 'positive' => 1, 'category' => $model->content_category, 'section' => $model->section], ['class' => 'label label-primary']);?>
                    <ul>
                    	<?php
                    	showArguments(1, $model);
                  		?>
                    </ul>
                </li>
                <li>
                	<span class="label label-danger"><i class="icon-minus-sign"></i><?=Yii::t('norm','Negative arguments')?></span> <?php generateStarIcons($model['ratingneg']);?>  <?= Html::a(Yii::t('button', 'Add'), ['norm/addargument', 'norm' => $model['id'], 'positive' => 0, 'category' => $model->content_category, 'section' => $model->section], ['class' => 'label label-primary']);?>
                    <ul>
						<?php
                    	showArguments(0, $model);
                  		?>
                    </ul>
                </li>
           </ul>
		</li>
	</ul>
</div>

<?php
/**
 * Function to show the arguments of the norm
 * @param unknown $type Type of the argument
 * @param unknown $model Norm model
 */
function showArguments($type, $model){
	$sql = 'select * from argument where type = '.$type.' && norm = '.$model['id'];
	$query = Argument::findBySql($sql);
	$dataProvider = new ActiveDataProvider(['query' => $query]);
	$models = $dataProvider->models;
	$rate = 0;
	foreach($models as $modelArgument){
		?><li>
			<?php
			$description = $modelArgument['description'];
			if(is_numeric($description)){
				$content = Content::findOne($description);
				echo 'Content such as '.Html::a(Html::encode($content['title']), ['/nam/content/view', 'id' => $modelArgument['description']], ['class' => '']) .' should not be published to upload this content ';
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }else{
				echo Html::encode($description)." ";
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }
			?>
	       <?php $content = '<form name="form" action="" method="get"> <input class="rating" data-max="5" data-min="1" id="input" type="number"/> </form>' ;?>
           <?php
	           if(ArgumentRate::isRated($modelArgument['id'])){
	           ?>	<span>Rate argument:<?php
	           	echo Html::a(Yii::t('button', '1'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>1, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->content_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '2'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>2, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->content_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '3'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>3, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->content_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '4'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>4, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->content_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '5'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>5, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->content_category], ['class' => 'glyphicon glyphicon-star']);
	           	?></span>
	           	<?php
	           }
	           ?>
	   	</li>
<?php }
}



function generateStarIcons($number){
	//Full star
	$num = floor($number);
	$rest = $number-$num;
	for($i=0; $i<$num; $i++){
		echo '<i class="fa fa-star yellow"></i>';
	}

	//Half star
	if($rest >= 0.5){
		echo '<i class="fa fa-star-half-empty yellow"></i>';
		$i++;
	}

	//Empty star
	for($j=$i; $j<5; $j++){
		echo '<i class="fa fa-star-o yellow"></i>';
	}
}
?>

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

common/modules/nam/views/norm/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use common\modules\nam\models\norm\Argument;
use yii\data\ActiveDataProvider;
use common\modules\nam\models\content\Content;
use common\modules\nam\models\norm\ArgumentRate;



/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('norm', 'Norms');
// $this->params['breadcrumbs'][] = $this->title;
?>
<br><br>
<?= Html::a(Yii::t('button', 'Create norm'), ['norm/createnorm'], ['class' => 'btn btn-primary']);?>
<br><br>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model, $key, $index, $widget) {
        	return $this->render('view',['model' => $model, 'section' => 1, 'status' => 1]);
        },
        'emptyText' => '',

        'layout' => '{items}{pager}'])
     ?>

<?php
/**
 * Function to show the arguments of the norm
 * @param unknown $type Type of the argument
 * @param unknown $model Norm model
 */
function showArguments($type, $model){
	$sql = 'select * from argument where type = '.$type.' && norm = '.$model['id'];
	$query = Argument::findBySql($sql);
	$dataProvider = new ActiveDataProvider(['query' => $query]);
	$models = $dataProvider->models;
	$rate = 0;
	foreach($models as $modelArgument){
		?><li>
			<?php
			$description = $modelArgument['description'];
			if(is_numeric($description)){
				$content = Content::findOne($description);
				echo 'Content such as '.Html::a(Html::encode($content['title']), ['/nam/content/view', 'id' => $modelArgument['description']], ['class' => '']) .' should not be published to upload this content ';
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }else{
				echo Html::encode($description)." ";
				echo generateStarIcons($modelArgument['rate']).'  ('.$modelArgument['numrate']?><i class="fa fa-user"></i><?php echo ')' ?>
			<?php }
			?>
	       <?php $content = '<form name="form" action="" method="get"> <input class="rating" data-max="5" data-min="1" id="input" type="number"/> </form>' ;?>
           <?php
	           if(ArgumentRate::isRated($modelArgument['id']) && (!$model->active)){
	           ?>	<span>Rate argument:<?php
	           	echo Html::a(Yii::t('button', '1'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>1, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '2'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>2, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '3'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>3, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '4'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>4, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	echo Html::a(Yii::t('button', '5'), ['norm/rate', 'id_argument' => $modelArgument['id'], 'rating' =>5, 'norm' => $model['id'], 'section' => $model->section, 'category' => $model->complain_category], ['class' => 'glyphicon glyphicon-star']);
	           	?></span>
	           	<?php
	           }
	           ?>
	   	</li>
<?php }
}


function generateStarIcons($number){
	//Full star
	$num = floor($number);
	$rest = $number-$num;
	echo '<i title="'.$number.'">';
	for($i=0; $i<$num; $i++){
		echo '<i class="fa fa-star yellow"></i>';
	}

	//Half star
	if($rest >= 0.5){
		echo '<i class="fa fa-star-half-empty yellow"></i>';
		$i++;
	}

	//Empty star
	for($j=$i; $j<5; $j++){
		echo '<i class="fa fa-star-o yellow"></i>';
	}
	echo '</i>';
}
?>

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">